# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd52495ad9aefc0e631f00d193135241d5b49e36f05b8dd128a9e0513b09cf4ef5bbc7965dffdd49bb07228a80f16b4f6afd4c7f82967ab7149a3190272a1c05

test:
  secret_key_base: 4fa67acbb9007bde130aac22b495754226f4db2d63ac0d5412ad661a6c064ee5c9c0b32b5215db56942ba8245367501a6118f45c8eaa67596f391b269c0e1783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
